default: &default
  adapter:  postgresql
  database: mmiworkshop
  host:     localhost
  username: postgres
  pool:     5
  timeout:  5000

development:
  <<: *default

  test:
  <<: *default
  adapter: postgresql
  database: mmiworkshop
